name: Weekly Log Analysis

on:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn user-agents pytz markdown

      - name: Fetch log file
        env:
          API_KEY: ${{ secrets.LOG_API_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "API_KEY is missing"
            exit 1
          fi
          curl -G "https://loucantou.yvelin.net/logs/loucantou-access.log?api_key=$API_KEY" \
            -o loucantou-access.log

      - name: Run traffic analysis
        run: |
          python analyse-traffic.py --period w --logpath loucantou-access.log

      - name: Get MD diff file
        id: get_md
        run: |
          echo $(git ls-files --modified)
          FILE=$(git ls-files --modified | grep -E '\.md$' | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No MD file found in diff."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "md_file=$FILE" >> "$GITHUB_OUTPUT"
            echo "md_content=$(cat $FILE)" >> "$GITHUB_OUTPUT"
          fi

      - name: Convert Markdown to HTML
        id: convert_md_to_html
        run: |
          python -c "
          import markdown, os;
          md_content = os.environ['MD_CONTENT'];
          html_content = markdown.markdown(md_content);
          print(f'::set-output name=html_content::{html_content}');
          "
        env:
          MD_CONTENT: ${{ steps.get_md.outputs.md_content }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Weekly Log Analysis
          from: Lou Cantou
          to: louisyvelin@gmail.com
          html_body: ${{ steps.convert_md_to_html.outputs.html_content }}

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Weekly log analysis update"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
          fi
