name: Weekly Log Analysis

on:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib seaborn user-agents pytz

      - name: Fetch log file
        env:
          API_KEY: ${{ secrets.LOG_API_KEY }}
        run: |
          if [ -z "$API_KEY" ]; then
            echo "API_KEY is missing"
            exit 1
          fi
          curl -G "https://loucantou.yvelin.net/logs/loucantou-access.log" \
            --data-urlencode "api_key=$API_KEY" \
            -o loucantou-access.log

      - name: Run traffic analysis
        run: |
          python analyse-traffic.py --period w --logpath loucantou-access.log

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Weekly log analysis update"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
          fi
